version: "3.9"
services:
  nginx_primary:
    image: my-nginx:latest
    ports:
     - "8080:80"
    environment:
      - NGINX_PORT=80

  nginx_secondary:
    image: my-nginx:latest
    ports:
      - "8181:80"
    environment:
      - NGINX_PORT=81

